language: php
php:
  - 5.6
  - 5.5
before_script:
  - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - phpunit --configuration ./test/unit/php/phpunit.xml