language: php
php:
  - 5.6
  - 5.5
  - 5.4
before_script:
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - phpunit --configuration ./test/unit/php/phpunit.xml